/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllGui;

import AllClasses.Update;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import AllClasses.*;


public class Admin_Update_Admin_Info extends javax.swing.JFrame {

   private String username;
    private String password ;
    private int id;
    
    /** Creates new form Admin_Update_Admin_Info */
    public Admin_Update_Admin_Info() {
        initComponents();
    }

    public Admin_Update_Admin_Info(String username,String password) {
        initComponents();
        this.username = username;
        this.password = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update_password = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        show_info = new javax.swing.JButton();
        admin_name = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        admin_age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        admin_username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        admin_old_password = new javax.swing.JPasswordField();
        admin_new_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        admin_con_new_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        update_name = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        update_age = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        update_username = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        update_password.setText("Update Password");
        update_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_passwordActionPerformed(evt);
            }
        });

        jLabel7.setText("Confirm New Password");

        show_info.setText("Show Info");
        show_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_infoActionPerformed(evt);
            }
        });

        Back.setText("Go Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        admin_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_ageActionPerformed(evt);
            }
        });
        admin_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                admin_ageKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Update My Info");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        update_name.setText("Update Name");
        update_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_nameActionPerformed(evt);
            }
        });

        jLabel4.setText("Usernamw");

        update_age.setText("Update Age");
        update_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ageActionPerformed(evt);
            }
        });

        jLabel5.setText("Old Password");

        update_username.setText("Update Username");
        update_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_usernameActionPerformed(evt);
            }
        });

        jLabel6.setText("New Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(show_info)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Back))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(124, 124, 124)
                                            .addComponent(admin_name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(168, 168, 168)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(admin_age, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                                .addComponent(admin_username)
                                                .addComponent(admin_old_password)
                                                .addComponent(admin_new_password)
                                                .addComponent(admin_con_new_password))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7)))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(update_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(update_password)
                                    .addComponent(update_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(update_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(admin_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(admin_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_age))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(admin_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_username))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(admin_old_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(admin_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(admin_con_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(show_info))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_passwordActionPerformed
        // TODO add your handling code here:

        if(admin_old_password.getText().isEmpty() || admin_new_password.getText().isEmpty() || admin_con_new_password.getText().isEmpty()){
            Masseges.showErrorDialog(Masseges.errorEmptyField);
        }else{
            try{
                if(admin_old_password.getText().equals(adminTasks.getInstance().oldPass(this.id,"ADMIN"))){

                    if(admin_new_password.getText().equals(admin_con_new_password.getText())){
                        Update updateMember = new Update();
                        updateMember.update(this.id,admin_new_password.getText(),"PASSWORD","ADMIN");
                        password = admin_new_password.getText();
                        Masseges.showInformationDialog("Update Succesfully");
                    }else{
                        Masseges.showErrorDialog("Password don't Match");
                    }

                }else{
                    Masseges.showErrorDialog("Wrong Old Password");
                }
            }catch (SQLException ex) {
                    Masseges.showErrorDialog(AllClasses.Masseges.errorUpdatingDatabase);
            }

        }
    }//GEN-LAST:event_update_passwordActionPerformed

    private void show_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_infoActionPerformed
        // TODO add your handling code here:
        System.out.println(this.username + " " + this.password);
        try{
            ArrayList<String> adminInformation = adminTasks.getInstance().searchUpdateAdmin(this.username, this.password );
            int counter = 0;
            String[] columnsName = {"ID", "Name","Age","Usersnem"};
            String[][] data = new String [(adminInformation.size())/4][4];
            for (int i = 0 ; i<data.length ; i++){
                for(int j=0 ; j<4 ; j++){
                    data[i][j] = adminInformation.get(counter);
                    if(i==0 && j==0)
                    id = Integer.parseInt(data[i][j]);
                    counter++;
                }
            }
            DefaultTableModel model = new DefaultTableModel(data, columnsName);
            table.setModel(model);
            table.setDefaultEditor(Object.class, null);
        }catch (SQLException ex) {
            Logger.getLogger(Admin_Update_Admin_Info.class.getName()).log(Level.SEVERE, null, ex);
            Masseges.showErrorDialog(AllClasses.Masseges.errorUpdatingDatabase);
        }
    }//GEN-LAST:event_show_infoActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Admin adminPage = new Admin();
        CenterFrame.setCenterScreen(this,adminPage);
    }//GEN-LAST:event_BackActionPerformed

    private void admin_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_ageActionPerformed

    private void admin_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_ageKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))){
            evt.consume();
        }
    }//GEN-LAST:event_admin_ageKeyTyped

    private void update_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_nameActionPerformed
        // TODO add your handling code here:

        if(admin_name.getText().isEmpty()){
            Masseges.showErrorDialog(AllClasses.Masseges.errorEmptyField);
        }else{
            try{
                Update updateMember = new Update();
                updateMember.update(this.id,admin_name.getText(),"NAME","ADMIN");
                Masseges.showInformationDialog("Update Succesfully");
            }catch (SQLException ex) {
                Masseges.showErrorDialog(AllClasses.Masseges.errorUpdatingDatabase);
            }
        }
    }//GEN-LAST:event_update_nameActionPerformed

    private void update_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ageActionPerformed
        // TODO add your handling code here:

        if(admin_age.getText().isEmpty()){
            Masseges.showErrorDialog(AllClasses.Masseges.errorEmptyField);
        }else{
            try{
                 Update update = new Update();
                update.updateAge(this.id,Integer.parseInt(admin_age.getText()),"ADMIN");
                Masseges.showInformationDialog("Update Succesfully");
            }catch (SQLException ex) {
                AllClasses.Masseges.showErrorDialog(AllClasses.Masseges.errorUpdatingDatabase);
            }
        }
    }//GEN-LAST:event_update_ageActionPerformed

    private void update_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_usernameActionPerformed
        // TODO add your handling code here:

        if(admin_username.getText().isEmpty()){
            Masseges.showErrorDialog(AllClasses.Masseges.errorEmptyField);
        }else{
            try{
                Update updateMember = new Update();
                updateMember.update(this.id,admin_username.getText(),"USERNAME","ADMIN");
                username = admin_username.getText();
                Masseges.showInformationDialog("Update Succesfully");
            }catch (SQLException ex) {
                Masseges.showErrorDialog(AllClasses.Masseges.errorUpdatingDatabase);
            }
        }
    }//GEN-LAST:event_update_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Admin_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Admin_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Admin_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Admin_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Update_Admin_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField admin_age;
    private javax.swing.JPasswordField admin_con_new_password;
    private javax.swing.JTextField admin_name;
    private javax.swing.JPasswordField admin_new_password;
    private javax.swing.JPasswordField admin_old_password;
    private javax.swing.JTextField admin_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton show_info;
    private javax.swing.JTable table;
    private javax.swing.JButton update_age;
    private javax.swing.JButton update_name;
    private javax.swing.JButton update_password;
    private javax.swing.JButton update_username;
    // End of variables declaration//GEN-END:variables
}
