/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllGui;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import java.util.logging.Level;
import java.util.logging.Logger;
import AllClasses.*;


public class Admin_Update_Memeber extends javax.swing.JFrame {

  private int id;
    
    /** Creates new form Admin_Update_Memeber */
    public Admin_Update_Memeber() {
        initComponents();
    }
    
    public Admin_Update_Memeber(int id) {
        initComponents();
        this.id=id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        member_username = new javax.swing.JTextField();
        member_old_password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        member_new_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        member_con_new_password = new javax.swing.JPasswordField();
        Back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        update_name = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        update_age = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        update_username = new javax.swing.JButton();
        member_age = new javax.swing.JTextField();
        member_name = new javax.swing.JTextField();
        update_password = new javax.swing.JButton();
        show_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Update Members");

        member_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_usernameActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Assigned Coach"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Usernamw");

        Back.setText("Go Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Old Password");

        update_name.setText("Update Name");
        update_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_nameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("New Password");

        update_age.setText("Update Age");
        update_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ageActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Confirm New Password");

        update_username.setText("Update Username");
        update_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_usernameActionPerformed(evt);
            }
        });

        member_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_ageActionPerformed(evt);
            }
        });
        member_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                member_ageKeyTyped(evt);
            }
        });

        update_password.setText("Update Password");
        update_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_passwordActionPerformed(evt);
            }
        });

        show_info.setText("Show Info");
        show_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(show_info)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Back))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update_username))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update_password))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(member_name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(158, 158, 158)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(member_age)
                                                .addComponent(member_username)
                                                .addComponent(member_old_password)
                                                .addComponent(member_new_password)
                                                .addComponent(member_con_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(update_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(update_name, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(member_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(member_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_age))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(member_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_username))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(member_old_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(member_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(member_con_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(show_info))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Admin_Search_Memeber searchMember = new Admin_Search_Memeber();
        CenterFrame.setCenterScreen(this,searchMember);
    }//GEN-LAST:event_BackActionPerformed

    private void update_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_nameActionPerformed
        // TODO add your handling code here:

        if(member_name.getText().isEmpty()){
            Masseges.showErrorDialog(AllClasses.Masseges.errorEmptyField);
        }else{
            try{
                Update updateMember = new Update();
                updateMember.update(this.id,member_name.getText(),"NAME","MEMBER");
                Masseges.showInformationDialog("Update Succesfully");
            }catch (SQLException ex) {
                Masseges.showErrorDialog(Masseges.errorUpdatingDatabase);
            }
        }

    }//GEN-LAST:event_update_nameActionPerformed

    private void update_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ageActionPerformed
        // TODO add your handling code here:

        if(member_age.getText().isEmpty()){
           Masseges.showErrorDialog(AllClasses.Masseges.errorEmptyField);
        }else{
            try{
                Update update = new Update();
                update.updateAge(this.id,Integer.parseInt(member_age.getText()),"MEMBER");
                Masseges.showInformationDialog("Update Succesfully");
            }catch (SQLException ex) {
                Masseges.showErrorDialog(Masseges.errorUpdatingDatabase);
            }
        }
    }//GEN-LAST:event_update_ageActionPerformed

    private void update_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_usernameActionPerformed
        // TODO add your handling code here:

        if(member_username.getText().isEmpty()){
            Masseges.showErrorDialog(AllClasses.Masseges.errorEmptyField);
        }else{
            try{
                Update updateMember = new Update();
                updateMember.update(this.id,member_username.getText(),"USERNAME","MEMBER");
                Masseges.showInformationDialog("Update Succesfully");
            }catch (SQLException ex) {
                Masseges.showErrorDialog(Masseges.errorUpdatingDatabase);
            }
        }
    }//GEN-LAST:event_update_usernameActionPerformed

    private void member_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_ageActionPerformed

    private void member_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_member_ageKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))){
            evt.consume();
        }
    }//GEN-LAST:event_member_ageKeyTyped

    private void update_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_passwordActionPerformed
        // TODO add your handling code here:

        if(member_old_password.getText().isEmpty() || member_new_password.getText().isEmpty() || member_con_new_password.getText().isEmpty()){
            Masseges.showErrorDialog(Masseges.errorEmptyField);
        }else{
            try{
                if(member_old_password.getText().equals(AllClasses.adminTasks.getInstance().oldPass(this.id,"MEMBER"))){
                    System.out.println("hi");
                    if(member_new_password.getText().equals(member_con_new_password.getText())){
                        Update updateMember = new Update();
                        updateMember.update(this.id,member_new_password.getText(),"PASSWORD","MEMBER");
                        Masseges.showInformationDialog("Update Succesfully");
                    }else{
                        Masseges.showErrorDialog("Password don't Match");
                    }

                }else{
                    Masseges.showErrorDialog("Wrong Old Password");
                }
            }catch (SQLException ex) {
                Logger.getLogger(Admin_Update_Memeber.class.getName()).log(Level.SEVERE, null, ex);
                Masseges.showErrorDialog(Masseges.errorUpdatingDatabase);
            }

        }
    }//GEN-LAST:event_update_passwordActionPerformed

    private void show_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_infoActionPerformed
        // TODO add your handling code here:

        try{
            SearchMember search = new SearchMember();
            ArrayList<String> member = search.searchMember(this.id);
            int counter = 0;
            String[] columnsName = {"ID", "Name","Age","Assigned Coach"};
            String[][] data = new String [(member.size())/4][4];
            for (int i = 0 ; i<data.length ; i++){
                for(int j=0 ; j<4 ; j++){
                    data[i][j] = member.get(counter);
                    counter++;
                }
            }
            DefaultTableModel model = new DefaultTableModel(data, columnsName);
            table.setModel(model);
            table.setDefaultEditor(Object.class, null);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_List_Coach.class.getName()).log(Level.SEVERE, null, ex);
            Masseges.showErrorDialog(Masseges.errorUpdatingDatabase);
        }

    }//GEN-LAST:event_show_infoActionPerformed

    private void member_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Update_Memeber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField member_age;
    private javax.swing.JPasswordField member_con_new_password;
    private javax.swing.JTextField member_name;
    private javax.swing.JPasswordField member_new_password;
    private javax.swing.JPasswordField member_old_password;
    private javax.swing.JTextField member_username;
    private javax.swing.JButton show_info;
    private javax.swing.JTable table;
    private javax.swing.JButton update_age;
    private javax.swing.JButton update_name;
    private javax.swing.JButton update_password;
    private javax.swing.JButton update_username;
    // End of variables declaration//GEN-END:variables
}
