/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllGui;

import AllGui.Admin_Add_Coach;
import AllGui.Admin_Add_Memeber;
import AllGui.Admin_Assign_Coach;
import AllGui.Admin_List_Coach;
import AllGui.Admin_List_Memeber;
import AllGui.Admin_Manage_Price;
import AllGui.Admin_Search_Coach;
import AllGui.Admin_Search_Memeber;
import AllGui.Admin_Update_Admin_Info;

public class Admin extends javax.swing.JFrame {

    private String username ;
    private String password ;

    /** Creates new form Admin */
    public Admin() {
        initComponents();
    }
    
    public Admin(String username,String password) {
        initComponents();
        this.username = username;
        this.password = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CoachAdd = new javax.swing.JButton();
        CoachSearch = new javax.swing.JButton();
        CoachList = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MemberAdd = new javax.swing.JButton();
        MemberList = new javax.swing.JButton();
        MemberSearch = new javax.swing.JButton();
        AssignCoach = new javax.swing.JButton();
        MangeBilling = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Log_Out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Update My Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Coaches", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        CoachAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CoachAdd.setText("Add");
        CoachAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachAddActionPerformed(evt);
            }
        });

        CoachSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CoachSearch.setText("Search");
        CoachSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachSearchActionPerformed(evt);
            }
        });

        CoachList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CoachList.setText("List All Coaches");
        CoachList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CoachAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoachList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoachSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoachAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CoachSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CoachList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Members", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        MemberAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MemberAdd.setText("Add");
        MemberAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberAddActionPerformed(evt);
            }
        });

        MemberList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MemberList.setText("List All Members");
        MemberList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberListActionPerformed(evt);
            }
        });

        MemberSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MemberSearch.setText("Search");
        MemberSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemberList)
                    .addComponent(MemberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MemberAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MemberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MemberList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AssignCoach.setText("Assign Coach");
        AssignCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignCoachActionPerformed(evt);
            }
        });

        MangeBilling.setText("Manage Prices");
        MangeBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangeBillingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        Log_Out.setText("Log-out");
        Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Log_Out)
                                .addGap(14, 14, 14))
                            .addComponent(MangeBilling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AssignCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MangeBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AssignCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Log_Out)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Admin_Update_Admin_Info updateAdmin = new Admin_Update_Admin_Info(this.username,this.password);
        AllClasses.CenterFrame.setCenterScreen(this,updateAdmin);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CoachAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachAddActionPerformed
        // TODO add your handling code here:
        Admin_Add_Coach addCoach = new Admin_Add_Coach();
        AllClasses.CenterFrame.setCenterScreen(this,addCoach);
    }//GEN-LAST:event_CoachAddActionPerformed

    private void CoachSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachSearchActionPerformed
        // TODO add your handling code here:
        Admin_Search_Coach searchCoach = new Admin_Search_Coach();
        AllClasses.CenterFrame.setCenterScreen(this,searchCoach);
    }//GEN-LAST:event_CoachSearchActionPerformed

    private void CoachListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachListActionPerformed
        // TODO add your handling code here:
        Admin_List_Coach listCoach = new Admin_List_Coach();
        AllClasses.CenterFrame.setCenterScreen(this,listCoach);
    }//GEN-LAST:event_CoachListActionPerformed

    private void MemberAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberAddActionPerformed
        // TODO add your handling code here:
        Admin_Add_Memeber addMember = new Admin_Add_Memeber();
        AllClasses.CenterFrame.setCenterScreen(this,addMember);
    }//GEN-LAST:event_MemberAddActionPerformed

    private void MemberListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberListActionPerformed
        // TODO add your handling code here:
        Admin_List_Memeber listMember = new Admin_List_Memeber();
        AllClasses.CenterFrame.setCenterScreen(this,listMember);
    }//GEN-LAST:event_MemberListActionPerformed

    private void MemberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberSearchActionPerformed
        // TODO add your handling code here:
        Admin_Search_Memeber searchMember = new Admin_Search_Memeber();
        AllClasses.CenterFrame.setCenterScreen(this,searchMember);
    }//GEN-LAST:event_MemberSearchActionPerformed

    private void AssignCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignCoachActionPerformed
        // TODO add your handling code here:
        Admin_Assign_Coach assignCoach = new Admin_Assign_Coach();
        AllClasses.CenterFrame.setCenterScreen(this,assignCoach);
    }//GEN-LAST:event_AssignCoachActionPerformed

    private void MangeBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangeBillingActionPerformed
        // TODO add your handling code here:
        Admin_Manage_Price manageBilling = new Admin_Manage_Price();
        AllClasses.CenterFrame.setCenterScreen(this,manageBilling);
    }//GEN-LAST:event_MangeBillingActionPerformed

    private void Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_OutActionPerformed
        AllGui.login frame2=new login();
        AllClasses.CenterFrame.setCenterScreen(this, frame2);

    }//GEN-LAST:event_Log_OutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignCoach;
    private javax.swing.JButton CoachAdd;
    private javax.swing.JButton CoachList;
    private javax.swing.JButton CoachSearch;
    private javax.swing.JButton Log_Out;
    private javax.swing.JButton MangeBilling;
    private javax.swing.JButton MemberAdd;
    private javax.swing.JButton MemberList;
    private javax.swing.JButton MemberSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
